"""Thin, reusable wrapper around the saved model pipeline: given raw feature
rows, returns a persistence probability and a heuristic risk category. Used
by evaluate.py, and by the FastAPI service (Phase 5) and dashboard (Phase 6)
so there's exactly one place that owns "how do we turn a probability into a
risk label."

Per-prediction "top contributing factors" (SHAP-based) are added in Phase 4
(src/student_journey/explainability/) and consumed by the API — not
duplicated here.

Calibration note: the saved model uses class_weight="balanced" to handle
class imbalance during training, which improves precision/recall/F1 on the
minority (non-persisting) class but is known to shift predicted
probabilities away from true base rates (see docs/screenshots/
calibration_curve.png, generated by evaluate.py, which shows predicted
probabilities running below observed persistence rates). Because of that,
risk categories are NOT fixed round-number probability cutoffs — they're
percentile thresholds over the model's own risk-score distribution on the
validation set (computed once in train.py, saved to model_metadata.json,
and loaded here), so "high risk" reliably means "the riskiest ~10% of
students by this model's ranking" rather than an absolute, miscalibrated
probability band. This is stated again in the API response disclaimer in
Phase 5.
"""
from __future__ import annotations

import json
import warnings
from dataclasses import dataclass

import joblib
import pandas as pd

from student_journey.config import MODELS_DIR
from student_journey.models.train import FEATURE_COLUMNS

MODEL_PATH = MODELS_DIR / "model_pipeline.joblib"
METADATA_PATH = MODELS_DIR / "model_metadata.json"


def risk_category(risk_probability: float, risk_thresholds: dict) -> str:
    """risk_thresholds: {"low_max": <p60 of val risk scores>, "medium_max": <p90>}"""
    if risk_probability < risk_thresholds["low_max"]:
        return "low"
    if risk_probability < risk_thresholds["medium_max"]:
        return "medium"
    return "high"


@dataclass
class PredictionResult:
    persistence_probability: float
    risk_probability: float
    risk_category: str


class PersistenceModel:
    """Loads the trained pipeline + metadata once; reused across predictions."""

    def __init__(self, model_path=MODEL_PATH, metadata_path=METADATA_PATH):
        if not model_path.exists():
            raise FileNotFoundError(f"{model_path} not found. Run `python -m student_journey.models.train` first.")
        self.pipeline = joblib.load(model_path)
        self.metadata = json.loads(metadata_path.read_text())
        self.model_version = self.metadata["model_version"]
        self.model_type = self.metadata["selected_model"]
        self.risk_thresholds = self.metadata["risk_thresholds"]

    def _validate_columns(self, df: pd.DataFrame) -> None:
        missing = set(FEATURE_COLUMNS) - set(df.columns)
        if missing:
            raise ValueError(f"Missing required feature columns: {sorted(missing)}")

    def predict_batch(self, df: pd.DataFrame) -> list[PredictionResult]:
        self._validate_columns(df)
        X = df[FEATURE_COLUMNS]
        with warnings.catch_warnings():
            warnings.filterwarnings("ignore", category=RuntimeWarning)
            persist_prob = self.pipeline.predict_proba(X)[:, 1]

        results = []
        for p in persist_prob:
            risk_prob = float(1.0 - p)
            results.append(
                PredictionResult(
                    persistence_probability=float(p),
                    risk_probability=risk_prob,
                    risk_category=risk_category(risk_prob, self.risk_thresholds),
                )
            )
        return results

    def predict_one(self, record: dict) -> PredictionResult:
        df = pd.DataFrame([record])
        return self.predict_batch(df)[0]


if __name__ == "__main__":
    # Smoke test: predict on a few rows straight from the features table.
    import sqlite3

    from student_journey.config import DB_PATH, FEATURES_TABLE

    conn = sqlite3.connect(DB_PATH)
    sample = pd.read_sql(
        f"SELECT * FROM {FEATURES_TABLE} WHERE persisted_next_term IS NOT NULL LIMIT 5", conn
    )
    conn.close()

    model = PersistenceModel()
    for record, result in zip(sample.to_dict(orient="records"), model.predict_batch(sample)):
        print(
            f"student {record['student_id']} term {record['term_number']}: "
            f"persist_prob={result.persistence_probability:.3f} "
            f"risk={result.risk_probability:.3f} ({result.risk_category})"
        )
